idf_component_register(SRCS "main.c"
                    "../components/mqtt/mqtt_test_client.c"
                    "../components/services/console/console.c"
                    "../components/services/console/monitor.c"
                    "local_ota.c"
                    "ui/home/home_ui.c"
                    "ui/home/sub_home/temp_humidity/home_temp_humidity.c"
                    "ui/home/sub_home/album/home_album.c"
                    "ui/home/sub_home/album/album.c"
                    "ui/home/sub_home/album/album_flash.c"
                    "ui/common/ui_back_button.c"
                    "ui/common/system_monitor_ui.c"
                    "ui/statusbar/statusbar_ui.c"
                    "ui/controlcenter/controlcenter_ui.c"
                    "ui/controlcenter/sysInfo/sys_info_ui.c"
                    "ui/developer_mode/touch_calibration_ui.c"
                    "ui/set/settings_ui.c"
                    "ui/set/wifi/wifi_settings_ui.c"
                    "ui/icon/icon.c"
                    "ui/front/ui_font.c"
                    INCLUDE_DIRS "." "../components/mqtt" "../components/services/console" "ui/home" "ui/home/sub_home/temp_humidity" "ui/home/sub_home/album" "ui/common" "ui/statusbar" "ui/controlcenter" "ui/controlcenter/sysInfo" "ui/developer_mode" "ui/set" "ui/set/wifi" "ui/front" "ui/icon"
                    REQUIRES lvgl lvgl_port ws2812b rgb_led spi_flash platform_log app_update esp_http_client heap console
                             environment_sensor system_time cpu_usage wifi_manager w25q64_test littlefs_vfs
                             littlefs_test platform greatlogger mqtt)
